// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nihbxagjxmgisztnngzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5paGJ4YWdqeG1naXN6dG5uZ3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjM4NzUsImV4cCI6MjA2MTU5OTg3NX0.ydbZK_WGY7nwF6cJNkIw6Z2N915t9mugTkrhuySKpto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);